# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from asyncio.windows_events import NULL
from PyQt5 import QtCore, QtGui, QtWidgets
import cv2, imutils
import numpy as np
import os
import face_recognition
from PyQt5.QtGui import QImage
from PyQt5.QtGui import QPixmap
from warn_add_dialog import Ui_Dialog_Warn_Add
from sucess_add_dialog import Ui_Dialog_Sucess_Add


class Ui_MainWindow_Add(object):
        def setupUi(self, MainWindow):
                self.myWindow = MainWindow
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(1127, 704)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")

                # Input Name Segment
                self.inputName = QtWidgets.QLineEdit(self.centralwidget)
                self.inputName.setGeometry(QtCore.QRect(890, 170, 221, 41))
                self.inputName.setStyleSheet("font: 24pt \"Arial\";\n"
                "border: 2px solid black;\n"
                "border-radius: 15px;")
                self.inputName.setObjectName("inputName")
                self.inputName.setText("")

                self.label_2 = QtWidgets.QLabel(self.centralwidget)
                self.label_2.setGeometry(QtCore.QRect(270, 30, 121, 41))
                self.label_2.setStyleSheet("font: 24pt \"Arial\";\n"
                "border: 2px solid black;\n"
                "border-radius: 15px;")
                self.label_2.setObjectName("label_2")

                self.label_3 = QtWidgets.QLabel(self.centralwidget)
                self.label_3.setGeometry(QtCore.QRect(700, 170, 181, 41))
                self.label_3.setStyleSheet("font: 20pt \"Arial\";\n"
                "border: 2px solid black;\n"
                "border-radius: 10px;")
                self.label_3.setObjectName("label_3")

                #Take Photo Button
                self.takePhotoButton = QtWidgets.QPushButton(self.centralwidget)
                self.takePhotoButton.setGeometry(QtCore.QRect(250, 590, 161, 41))
                self.takePhotoButton.setStyleSheet("font: 18pt \"Arial\";\n"
                "border: 2px solid black;\n"
                "border-radius: 7px;\n"
                "background-color: grey;")
                self.takePhotoButton.setObjectName("takePhotoButton")
                self.takePhotoButton.clicked.connect(self.buttonClickOnListener)

                #Camera View Segment
                self.cameraView = QtWidgets.QLabel(self.centralwidget)
                self.cameraView.setGeometry(QtCore.QRect(20, 90, 621, 481))
                self.cameraView.setStyleSheet("border: 2px solid black;\n"
                "border-radius: 10px;\n"
                "")
                self.cameraView.setText("")
                self.cameraView.setObjectName("cameraView")

                #Input NPM Segment
                self.inputNpm = QtWidgets.QLineEdit(self.centralwidget)
                self.inputNpm.setGeometry(QtCore.QRect(890, 240, 221, 41))
                self.inputNpm.setStyleSheet("font: 24pt \"Arial\";\n"
                "border: 2px solid black;\n"
                "border-radius: 15px;")
                self.inputNpm.setObjectName("inputNpm")
                self.inputNpm.setText("")

                self.label_5 = QtWidgets.QLabel(self.centralwidget)
                self.label_5.setGeometry(QtCore.QRect(790, 100, 181, 41))
                self.label_5.setStyleSheet("font: 24pt \"Arial\";")
                self.label_5.setObjectName("label_5")
                self.label_4 = QtWidgets.QLabel(self.centralwidget)
                self.label_4.setGeometry(QtCore.QRect(700, 240, 181, 41))
                self.label_4.setStyleSheet("font: 20pt \"Arial\";\n"
                "border: 2px solid black;\n"
                "border-radius: 10px;")
                self.label_4.setObjectName("label_4")

                self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_3.setGeometry(QtCore.QRect(800, 400, 161, 41))
                self.pushButton_3.setStyleSheet("font: 18pt \"Arial\";\n"
                "border: 2px solid black;\n"
                "border-radius: 7px;\n"
                "background-color: grey;")
                self.pushButton_3.setObjectName("pushButton_3")
                self.pushButton_3.clicked.connect(self.check)

                self.label_6 = QtWidgets.QLabel(self.centralwidget)
                self.label_6.setGeometry(QtCore.QRect(700, 310, 181, 41))
                self.label_6.setStyleSheet("font: 20pt \"Arial\";\n"
                "border: 2px solid black;\n"
                "border-radius: 10px;")
                self.label_6.setObjectName("label_6")

                #Input Year Segment
                self.inputYear = QtWidgets.QLineEdit(self.centralwidget)
                self.inputYear.setGeometry(QtCore.QRect(890, 310, 221, 41))
                self.inputYear.setStyleSheet("font: 24pt \"Arial\";\n"
                "border: 2px solid black;\n"
                "border-radius: 15px;")
                self.inputYear.setObjectName("inputYear")
                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 1127, 26))
                self.menubar.setObjectName("menubar")
                MainWindow.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

                self.flags = 0
                self.cameraRun = True
                self.absenWindow = NULL
                self.studentsOnAddWindow = NULL
                

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.label_2.setText(_translate("MainWindow", "VIEW"))
                self.label_3.setText(_translate("MainWindow", "NAMA :"))
                self.takePhotoButton.setText(_translate("MainWindow", "Open Cam"))
                self.label_5.setText(_translate("MainWindow", "ISI DATA"))
                self.label_4.setText(_translate("MainWindow", "NPM :"))
                self.pushButton_3.setText(_translate("MainWindow", "SUBMIT"))
                self.label_6.setText(_translate("MainWindow", "YEAR :"))
        
        def buttonClickOnListener(self):
                self.retake()
        
        def check(self):
                self.cameraRun = False
                self.takePhoto()
                

        def retake(self):
                        #buat camera
                        cam = cv2.VideoCapture(0, cv2.CAP_DSHOW)
                        while True and self.cameraRun:
                                ret, frame = cam.read()
                                self.image = frame 
                                self.setPhoto(self.image)
                                k=cv2.waitKey(1)
                                if k%256 == 27:
                                        print("esc kluar")
                                        cam.release()
                                        cam.destroyAllWindows
                                        break
        
        def setPhoto(self, image):
                image = imutils.resize(image,width=640)
                frame = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
                image = QImage(frame, frame.shape[1],frame.shape[0],frame.strides[0],QImage.Format_RGB888)
                self.cameraView.setPixmap(QtGui.QPixmap.fromImage(image))
        
        def takePhoto(self):
                #
                if(self.inputName.text() == "" and self.inputNpm.text() == ""):
                        print("Handling")
                        self.inputName.setText("Fill Name!!")
                        self.inputNpm.setText("Fill NPM!!")
                        self.inputYear.setText("Fill Year!!")
                        self.cameraRun = True
                else:
                        wajahDir = 'fotowajah'
                        img_name = self.inputName.text() + "_" + self.inputNpm.text() + ".png"
                        cv2.imwrite(wajahDir + '/' +img_name, self.image)
                        self.studentsOnAddWindow.append(self.inputName.text().lower() + "_" + self.inputNpm.text().lower())
                        self.Dialog = QtWidgets.QDialog()
                        self.ui = Ui_Dialog_Sucess_Add()
                        self.ui.setupUi(self.Dialog)
                        self.ui.mainWindowBefore = self.myWindow
                        self.ui.daftarWindow = self.absenWindow
                        self.Dialog.show()


