# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog2(object):
    def setupUi(self, Dialog):
        self.myDialog = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(268, 215)
        self.infoLabel = QtWidgets.QLabel(Dialog)
        self.infoLabel.setGeometry(QtCore.QRect(10, 40, 251, 41))
        self.infoLabel.setStyleSheet("font: 75 18pt \"Arial\";\n"
"border: 2px solid;\n"
"border-radius: 10px;")
        self.infoLabel.setObjectName("infoLabel")
        self.infoButton = QtWidgets.QPushButton(Dialog)
        self.infoButton.setGeometry(QtCore.QRect(80, 150, 93, 28))
        self.infoButton.setObjectName("infoButton")
        self.infoButton.clicked.connect(self.buttonClick)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.infoLabel.setText(_translate("Dialog", "Login Failed"))
        self.infoButton.setText(_translate("Dialog", "OKAYY"))

    def buttonClick(self):
        self.myDialog.close()

