# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui3-reference.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1127, 707)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 80, 621, 481))
        self.label.setStyleSheet("border: 2px solid black;\n"
"border-radius: 10px;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 30, 121, 41))
        self.label_2.setStyleSheet("font: 24pt \"Arial\";\n"
"border: 2px solid black;\n"
"border-radius: 15px;")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 580, 161, 41))
        self.pushButton.setStyleSheet("font: 18pt \"Arial\";\n"
"border: 2px solid black;\n"
"border-radius: 7px;\n"
"background-color: grey;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 580, 161, 41))
        self.pushButton_2.setStyleSheet("font: 18pt \"Arial\";\n"
"border: 2px solid black;\n"
"border-radius: 7px;\n"
"background-color: grey;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.outputName = QtWidgets.QLineEdit(self.centralwidget)
        self.outputName.setGeometry(QtCore.QRect(890, 330, 221, 41))
        self.outputName.setStyleSheet("font: 24pt \"Arial\";\n"
"border: 2px solid black;\n"
"border-radius: 15px;")
        self.outputName.setObjectName("outputName")

        self.outputNpm = QtWidgets.QLineEdit(self.centralwidget)
        self.outputNpm.setGeometry(QtCore.QRect(890, 400, 221, 41))
        self.outputNpm.setStyleSheet("font: 24pt \"Arial\";\n"
"border: 2px solid black;\n"
"border-radius: 15px;")
        self.outputNpm.setObjectName("outputNpm")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(700, 330, 181, 41))
        self.label_3.setStyleSheet("font: 20pt \"Arial\";\n"
"border: 2px solid black;\n"
"border-radius: 10px;")
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(700, 400, 181, 41))
        self.label_4.setStyleSheet("font: 20pt \"Arial\";\n"
"border: 2px solid black;\n"
"border-radius: 10px;")
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(770, 260, 251, 41))
        self.label_5.setStyleSheet("font: 24pt \"Arial\";")
        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(700, 520, 181, 41))
        self.label_6.setStyleSheet("font: 20pt \"Arial\";\n"
"border: 2px solid black;\n"
"border-radius: 10px;")
        self.label_6.setObjectName("label_6")

        self.outputAbsensi = QtWidgets.QLineEdit(self.centralwidget)
        self.outputAbsensi.setGeometry(QtCore.QRect(890, 520, 221, 41))
        self.outputAbsensi.setStyleSheet("font: 24pt \"Arial\";\n"
"border: 2px solid black;\n"
"border-radius: 15px;")
        self.outputAbsensi.setObjectName("outputAbsensi")

        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(700, 460, 181, 41))
        self.label_7.setStyleSheet("font: 20pt \"Arial\";\n"
"border: 2px solid black;\n"
"border-radius: 10px;")
        self.label_7.setObjectName("label_7")

        self.outputTime = QtWidgets.QLineEdit(self.centralwidget)
        self.outputTime.setGeometry(QtCore.QRect(890, 460, 221, 41))
        self.outputTime.setStyleSheet("font: 24pt \"Arial\";\n"
"border: 2px solid black;\n"
"border-radius: 15px;")
        self.outputTime.setObjectName("outputTime")

        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(870, 110, 55, 16))
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1127, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "VIEW"))
        self.pushButton.setText(_translate("MainWindow", "Off Camera"))
        self.pushButton_2.setText(_translate("MainWindow", "On Camera"))
        self.label_3.setText(_translate("MainWindow", "NAMA :"))
        self.label_4.setText(_translate("MainWindow", "NPM :"))
        self.label_5.setText(_translate("MainWindow", "MAHASISWA"))
        self.label_6.setText(_translate("MainWindow", "ABSENSI :"))
        self.label_7.setText(_translate("MainWindow", "TIME :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
