# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'success_add_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from asyncio.windows_events import NULL
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Sucess_Add(object):
    def setupUi(self, Dialog):
        self.myDialog = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(150, 210, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.onClickListener)
        
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 50, 361, 111))
        self.label.setStyleSheet("font: 87 12pt \"Arial Black\";")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.mainWindowBefore = NULL
        self.daftarWindow = NULL

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "YOII"))
        self.label.setText(_translate("Dialog", "Success Adding New Data\n"
        "and Picrue. GG Dah"))

    def onClickListener(self):
        self.mainWindowBefore.close()
        self.myDialog.close()
        self.daftarWindow.show()

